# Generated by Django 2.0.2 on 2018-02-15 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.IntegerField(default=0)),
                ('mailcount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MailCollected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mailBox', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartboxWeb.MailBox')),
            ],
        ),
        migrations.AddField(
            model_name='deliveredpost',
            name='mailBox',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartboxWeb.MailBox'),
        ),
    ]
