# Generated by Django 2.0.2 on 2018-02-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartboxWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.IntegerField(default=0)),
                ('mailcount', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliveredpost',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='mailcollected',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.AddField(
            model_name='deliveredpost',
            name='mailBox',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartboxWeb.MailBox'),
        ),
        migrations.AddField(
            model_name='mailcollected',
            name='mailBox',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='smartboxWeb.MailBox'),
        ),
    ]
